name: Task 3

on:
  push:
    branches: [main,develop]
  workflow_dispatch:
        
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  main:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      run: |
        echo "npm install"

    - name: Migration
      run: |
        echo "Running migrations"

    - name: Tests
      run: echo "Running tests with Node ${{ matrix.node-version }}"

