name: Task 3

on:
  push:
    branches: [main,develop]
  workflow_dispatch:
        
jobs:
  main:
    runs-on: self-hosted
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16, 18, 20]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with: ${{matrix.node-version}}

    - name: Migration
      run: |
        echo "Running migrations"

    - name: Tests
      run: |
        echo "Running tests with Node ${{ matrix.node-version }}"
        echo "Test result" > ~/test-results-node-${{ matrix.node-version }}.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifact_node_v_${{ matrix.node-version }}
        path: ~/test-results-node-${{ matrix.node-version }}.txt
      

